### ISSUE TITLE
7x-1.0 - Full Release Checklist

### ISSUE THREAD

**Issue by mmilutinovic013** [mmilutinovic1313/easycdn#3]
**Initial Building Tasks**
- [x] Build App (will be broken into other tasks).
- [x] Test easyCDN works on all ELMS:LN systems
- [x] Verify that working on vanilla Drupal
- [x] Submit to d.o. 

**Improvements for a full-release**
- [x] Populate the version dropdown with versions from CDNs
- [ ] Option for using most recent version if local version isn't available on the CDN.
- [ ] Option for using the closest version if local version isn't available on the CDN. 
- [ ] Store CDN entry for each library as configurable/alterable "entity"
- [ ] Logic to tell if the library exists on a specific CDN or not (i.e. annyang is not on jsDelivr).
- [ ] Get Header add Access-Control-Allow-Origin "*" support if needed based on remote jquery making ajax calls" section.

I will make individual issues on github & drupal to track progress and check these branches off.
